### ISSUE TITLE
File download problems

### ISSUE THREAD

**Issue by huyongf** [csofranz/DML#2]
Hello my friend, I want to learn how to use your DML, but DML Documentation.pdf can not be downloaded, can you send me a separate copy via email, thank you! My email is: 83426074@qq.com. Thank you very much!

**Comment by csofranz** [comment]
Thank you for your message. I've now verified that you can download the entire archive as zip (much smaller than the pdf :) ), and that the documentation is intact. Can I bother you to please try again?

Thank you,
-ch

**Comment by huyongf** [comment]
Thank you very much! I've downloaded it in its entirety, started learning, and will ask you for help if I run into any problems! Thanks again!

**Comment by csofranz** [comment]
Enjoy :)
