### ISSUE TITLE
Recon Mode detects "Late Activated" and Late Activated Planes detecting things without existing

### ISSUE THREAD

**Issue by BigMongostyler** [csofranz/DML#5]
Recon-Units detecting "Late Activated" ground units 
and "Late Activated" Planes detecting things without existing.

If you got a "workaround" or a solution for this, lemee know.. 
I just wanted to use the dml´s recon mode for our servers, but cause of this issue i can not.. 

Lg
Dennis aka BigMongostyler

**Comment by csofranz** [comment]
Sorry for the delay in response, I was on the road for a couple of weeks. The issue you describe is new, do you perhaps have a screenshot of the offending messages and a miz file that demonstrates what is happening?

Thank you,
-ch

**Comment by BigMongostyler** [comment]
Yea.. cause its a while ago i could reproduce this 4 you..
just gimme time till Monday
